feat: sl-74 connection added
ychepel/second-life.backend pull request #6
Opened 2024-05-30 12:56 UTC by RS882

added connection between user and category

2024-05-30 15:19 UTC, Algalon1 requested changes

2024-05-30 17:46 UTC, ychepel commented on src/main/java/de/ait/secondlife/services/OfferServiceImpl.java
> +    private final CategoriesRepository categoriesRepository;
useless initialization of CategoriesRepository

2024-05-31 09:34 UTC, Algalon1 approved these changes

2024-05-31 10:38 UTC, ychepel approved these changes

2024-05-31 10:38 UTC, merged